name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

env:
  REGISTRY: "registry.digitalocean.com/wenchonglee"
  IMAGE_NAME: "rich-text-sync"
  TAG: "latest"

jobs:
  build_and_push:
    name: Build and start
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            # Git pull
            cd rich-text-sync
            git pull

            # Rebuild images images
            docker-compose build

            # Start services
            # NOTE: there exists a docker-compose.override.yml on the droplet that handles https
            docker-compose up -d 

            # Prune and cleanup dangling images
            docker image prune -a --force --filter "until=24h"
